package com.laosun.aluminium.test;

import com.laosun.aluminium.enums.TriggerEvent;
import com.laosun.aluminium.models.Character;
import com.laosun.aluminium.utils.CharacterFactory;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

/**
 * Every character rule\u2019s conditions, written out LITERALLY (2026-09-30).
 *
 * <p>\u26a0 Why literal: a judge that compares the file against the compiled table stays green when a mutation changes
 * both sides together (measured). To catch \u300cthe content itself was changed\u300d the expectation must live here. The
 * literals are the parser\u2019s spelling: attribute names lowered, integral thresholds given a decimal point.
 *
 * <p>\u2b50 Generated from the shipped files; regenerate after any condition change (see GAPS.md).
 */
public class CharacterConditionLiteralsTest {
    private static final int LEVEL = 80;

    private void assertRule(int cid, String event, String id, List<String> expected) {
        Character c = CharacterFactory.create(cid, LEVEL);
        var rules = c.getTriggerTable().rulesFor(TriggerEvent.valueOf(event)).stream()
                .filter(r -> r.id().equals(id)).toList();
        Assertions.assertEquals(1, rules.size(), cid + " " + id + " on " + event);
        var actual = rules.getFirst().conditions().stream().map(x -> x.source()).toList();
        Assertions.assertEquals(expected, actual, cid + " " + id);
    }

    @Test
    public void everyRuleWaitsForExactlyWhatItSays() {
        assertRule(1001, "SKILL_CAST", "skill_shield", List.of("actor == self"));
        assertRule(1001, "SKILL_CAST", "skill_soft_aggro", List.of("actor == self", "target_hp_percent >= 0.3"));
        assertRule(1001, "TAKING_HIT", "counter", List.of("target has_shield", "!actor is_ally"));
        assertRule(1001, "ULT_CAST", "ultimate_freeze", List.of("actor == self"));
        assertRule(1002, "SKILL_CAST", "talent_wind_pen", List.of("actor is_ally", "target == self"));
        assertRule(1002, "BATTLE_START", "level_convention", List.of());
        assertRule(1002, "BATTLE_START", "technique_opening_attack", List.of("self has_state 秘技"));
        assertRule(1002, "HP_LOST", "trace_low_hp_aggro_down", List.of("target == self", "hp_percent <= 0.5"));
        assertRule(1002, "HEALED", "trace_low_hp_aggro_down_cleanup", List.of("target == self", "hp_percent > 0.5"));
        assertRule(1003, "DEALING_DAMAGE", "starhunt_low_hp_damage", List.of("actor == self", "target_hp_percent <= 0.5"));
        assertRule(1004, "ULT_CAST", "ult_imprison", List.of("actor == self"));
        assertRule(1004, "BATTLE_START", "level_convention", List.of());
        assertRule(1004, "SKILL_CAST", "skill_speed_down", List.of("actor == self"));
        assertRule(1005, "ULT_CAST", "ult_shock_and_tick", List.of("actor == self"));
        assertRule(1005, "BATTLE_START", "level_convention", List.of());
        assertRule(1005, "ALLY_ATTACK", "talent_followup", List.of("actor is_other_ally", "from_skill COMMON"));
        assertRule(1005, "ULT_CAST", "trace_shock_lasts_one_more_turn", List.of("actor == self"));
        assertRule(1005, "FOLLOW_UP", "talent_dot_taken_on_followup", List.of("actor == self"));
        assertRule(1006, "ULT_CAST", "ult_defence_down", List.of("actor == self"));
        assertRule(1006, "BATTLE_START", "level_convention", List.of());
        assertRule(1006, "SKILL_CAST", "skill_all_type_res_down", List.of("actor == self"));
        assertRule(1008, "KILL", "trace_survival_heal", List.of("actor == self", "hp_percent <= 0.3"));
        assertRule(1008, "BATTLE_START", "trace_endurance_dot_resist", List.of());
        assertRule(1008, "BATTLE_START", "level_convention", List.of());
        assertRule(1009, "ULT_CAST", "ult_flat_speed_for_all_allies", List.of("actor == self"));
        assertRule(1009, "BATTLE_START", "technique_opening_aoe", List.of("self has_state 秘技"));
        assertRule(1009, "BATTLE_START", "level_convention", List.of());
        assertRule(1013, "BATTLE_START", "trace_puppet_control_resist", List.of());
        assertRule(1013, "BATTLE_START", "level_convention", List.of());
        assertRule(1013, "DEALING_DAMAGE", "skill_bonus_on_healthy_targets", List.of("actor == self", "from_skill SKILL", "target_hp_percent >= 0.5"));
        assertRule(1013, "DEALING_DAMAGE", "trace_ice_against_frozen", List.of("actor == self", "from_skill ULTRA", "target has_state 冻结"));
        assertRule(1013, "ULT_CAST", "eidolon6_attack", List.of("actor == self"));
        assertRule(1101, "ULT_CAST", "ult_party_attack", List.of("actor == self"));
        assertRule(1101, "ULT_CAST", "ult_party_crit_damage", List.of("actor == self"));
        assertRule(1102, "HP_LOST", "trace_low_hp_aggro_down", List.of("target == self", "hp_percent <= 0.5"));
        assertRule(1102, "HEALED", "trace_low_hp_aggro_down_cleanup", List.of("target == self", "hp_percent > 0.5"));
        assertRule(1103, "SKILL_CAST", "skill_shock", List.of("actor == self"));
        assertRule(1104, "SKILL_CAST", "skill_daunting_smite", List.of("actor == self"));
        assertRule(1104, "ULT_CAST", "ult_enduring_bulwark", List.of("actor == self"));
        assertRule(1104, "BATTLE_START", "trace_steadfast_aggro", List.of());
        assertRule(1104, "TURN_START", "trace_battle_will", List.of("actor == self"));
        assertRule(1104, "BATTLE_START", "eidolon1_freeze_chance", List.of());
        assertRule(1104, "BATTLE_START", "eidolon3_levels", List.of());
        assertRule(1104, "BATTLE_START", "eidolon4_party_resistance", List.of());
        assertRule(1104, "BATTLE_START", "eidolon5_levels", List.of());
        assertRule(1104, "BATTLE_START", "technique_opening_shield", List.of("self has_state 秘技"));
        assertRule(1105, "SKILL_CAST", "trace_conditioning", List.of("actor == self"));
        assertRule(1105, "BASIC_ATTACK", "trace_max_hp_additional_damage", List.of("actor == self"));
        assertRule(1106, "SKILL_CAST", "skill_dispel_buff", List.of("actor == self"));
        assertRule(1106, "ULT_CAST", "ult_zone_suppression", List.of("actor == self"));
        assertRule(1106, "BATTLE_START", "technique_defence_down", List.of("self has_state 秘技"));
        assertRule(1107, "BATTLE_START", "technique_taunt_aggro", List.of("self has_state 秘技"));
        assertRule(1107, "ULT_CAST", "eidolon2_attack_after_ult", List.of("actor == self"));
        assertRule(1108, "ULT_CAST", "ult_present", List.of("actor == self"));
        assertRule(1108, "DEALING_DAMAGE", "talent_windtorn", List.of("actor == self"));
        assertRule(1109, "SKILL_CAST", "skill_burn", List.of("actor == self"));
        assertRule(1109, "ULT_CAST", "trace_play_with_fire", List.of("actor == self"));
        assertRule(1109, "BATTLE_START", "eidolon2_longer_burn", List.of());
        assertRule(1109, "DEALING_DAMAGE", "eidolon6_bonus_against_burning", List.of("actor == self", "target has_state 灼烧"));
        assertRule(1109, "BATTLE_START", "eidolon3_levels", List.of());
        assertRule(1109, "BATTLE_START", "eidolon5_levels", List.of());
        assertRule(1109, "DEALING_DAMAGE", "talent_followup_against_burning", List.of("actor == self", "target has_state 灼烧", "damage_is_attack"));
        assertRule(1109, "DEALING_DAMAGE", "trace_childlike", List.of("actor == self", "target has_state 灼烧", "damage_is_attack"));
        assertRule(1109, "BATTLE_START", "trace_innocence", List.of());
        assertRule(1110, "SKILL_CAST", "skill_survival_response", List.of("actor == self"));
        assertRule(1110, "SKILL_CAST", "talent_regen_after_skill", List.of("actor == self"));
        assertRule(1110, "ULT_CAST", "ult_first_aid", List.of("actor == self"));
        assertRule(1110, "ULT_CAST", "talent_regen_after_ult", List.of("actor == self"));
        assertRule(1111, "ULT_CAST", "ult_coup", List.of("actor == self"));
        assertRule(1111, "BATTLE_START", "talent_start", List.of());
        assertRule(1111, "ALLY_ATTACK", "talent_after_basic", List.of("actor == self", "from_skill COMMON"));
        assertRule(1111, "ALLY_ATTACK", "talent_enhance_basic", List.of("actor == self", "self_stacks:斗志 >= 2.0"));
        assertRule(1111, "ALLY_ATTACK", "talent_enhanced_laceration", List.of("actor == self", "from_skill_id == 8.0", "target has_state 裂伤"));
        assertRule(1111, "ALLY_ATTACK", "enhanced_costs_two_layers", List.of("actor == self", "from_skill_id == 8.0"));
        assertRule(1111, "ALLY_ATTACK", "talent_after_skill", List.of("actor == self", "from_skill SKILL"));
        assertRule(1111, "SKILL_CAST", "trace_overload", List.of("actor == self"));
        assertRule(1111, "SKILL_CAST", "skill_lacerate", List.of("actor == self"));
        assertRule(1112, "DEALING_DAMAGE", "trace_damage_vs_fire_weakness", List.of("actor == self", "target has_weakness Fire"));
        assertRule(1112, "SKILL_CAST", "skill_proof_of_debt", List.of("actor == self"));
        assertRule(1112, "BATTLE_START", "level_convention", List.of());
        assertRule(1201, "TURN_START", "talent_draw_on_ally_turn", List.of("actor is_other_ally"));
        assertRule(1201, "BATTLE_START", "technique_draw", List.of("self has_state 秘技"));
        assertRule(1201, "SKILL_CAST", "skill_damage_up_stacks", List.of("actor == self"));
        assertRule(1201, "SKILL_CAST", "skill_draw_tiles", List.of("actor == self"));
        assertRule(1201, "BATTLE_START", "level_convention", List.of());
        assertRule(1202, "SKILL_CAST", "skill_benediction", List.of("actor == self"));
        assertRule(1202, "ULT_CAST", "ult_energy_and_boost", List.of("actor == self"));
        assertRule(1202, "SKILL_CAST", "trace_speed_on_skill", List.of("actor == self"));
        assertRule(1202, "DEALING_DAMAGE", "trace_basic_attack_boost", List.of("actor == self", "from_skill COMMON"));
        assertRule(1202, "TURN_START", "trace_energy_at_turn_start", List.of("actor == self"));
        assertRule(1202, "BATTLE_START", "level_convention", List.of());
        assertRule(1203, "SKILL_CAST", "skill_abyss_flower", List.of("actor == self"));
        assertRule(1203, "BATTLE_START", "level_convention", List.of());
        assertRule(1203, "HP_LOST", "skill_trigger_on_crossing", List.of("target_hp_percent <= 0.5", "target_hp_percent_before > 0.5"));
        assertRule(1203, "ULT_CAST", "ult_all_type_res_down", List.of("actor == self"));
        assertRule(1204, "BATTLE_START", "level_convention", List.of());
        assertRule(1204, "SKILL_CAST", "trace_dispatch_crit_chance", List.of("actor == self"));
        assertRule(1205, "SKILL_CAST", "skill_hellscape_state", List.of("actor == self"));
        assertRule(1205, "BATTLE_START", "technique_opening_aoe", List.of("self has_state 秘技"));
        assertRule(1205, "TAKING_HIT", "talent_charge_on_hit", List.of("target == self"));
        assertRule(1205, "BATTLE_START", "level_convention", List.of());
        assertRule(1205, "TURN_START", "eidolon2_crit_while_hellscape", List.of("self has_state 地狱变"));
        assertRule(1206, "BREAK", "talent_speed_on_break", List.of());
        assertRule(1206, "ALLY_ATTACK", "skill_sword_stance_chance", List.of("actor == self", "from_skill SKILL", "!target has_state 弱点击破"));
        assertRule(1206, "ALLY_ATTACK", "skill_sword_stance_guaranteed", List.of("actor == self", "from_skill SKILL", "target has_state 弱点击破"));
        assertRule(1206, "BATTLE_START", "level_convention", List.of());
        assertRule(1206, "BATTLE_START", "technique_opening_damage", List.of("self has_state 秘技"));
        assertRule(1206, "HP_LOST", "trace_low_hp_aggro_down", List.of("target == self", "hp_percent <= 0.5"));
        assertRule(1206, "HEALED", "trace_low_hp_aggro_down_cleanup", List.of("target == self", "hp_percent > 0.5"));
        assertRule(1207, "SKILL_CAST", "skill_command", List.of("actor == self"));
        assertRule(1208, "BATTLE_START", "talent_misfortune_avoidance", List.of());
        assertRule(1208, "SKILL_CAST", "skill_knowledge_state_and_modifiers", List.of("actor == self"));
        assertRule(1208, "SKILL_CAST", "eidolon1_knowledge_crit_damage", List.of("actor == self"));
        assertRule(1208, "BATTLE_START", "level_convention", List.of());
        assertRule(1209, "SKILL_CAST", "skill_soulsteel_sync_and_its_modifiers", List.of("actor == self"));
        assertRule(1209, "ULT_CAST", "ult_crit_chance_on_self", List.of("actor == self"));
        assertRule(1209, "ULT_CAST", "ult_extra_crit_damage_when_synced", List.of("actor == self", "self has_state 智剑连心"));
        assertRule(1209, "ALLY_ATTACK", "talent_chance_followup", List.of("actor == self"));
        assertRule(1209, "BATTLE_START", "level_convention", List.of());
        assertRule(1209, "SKILL_CAST", "trace_effect_res_while_synced", List.of("actor == self"));
        assertRule(1211, "ULT_CAST", "ult_rebirth", List.of("actor == self"));
        assertRule(1212, "SKILL_CAST", "skill_syzygy_stack", List.of("actor == self"));
        assertRule(1212, "ULT_CAST", "ult_syzygy_stack", List.of("actor == self"));
        assertRule(1212, "SKILL_CAST", "talent_transmigration_at_two_stacks", List.of("actor == self", "self_stacks:朔望 >= 2.0"));
        assertRule(1212, "BATTLE_START", "level_convention", List.of());
        assertRule(1212, "HP_CONSUMED", "talent_moon_on_hp_consumed", List.of("self has_state 转魄"));
        assertRule(1212, "TAKING_HIT", "talent_moon_on_damage", List.of("self has_state 转魄"));
        assertRule(1213, "DEALING_DAMAGE", "talent_righteous_heart", List.of("actor == self"));
        assertRule(1213, "BATTLE_START", "level_convention", List.of());
        assertRule(1214, "BATTLE_START", "technique_opening_aoe", List.of("self has_state 秘技"));
        assertRule(1214, "BATTLE_START", "level_convention", List.of());
        assertRule(1214, "ULT_CAST", "eidolon4_breaking_effect", List.of("actor == self"));
        assertRule(1215, "ULT_CAST", "ult_blessing", List.of("actor == self", "target != self"));
        assertRule(1215, "DEALING_DAMAGE", "talent_common", List.of("target has_state 承负", "actor is_ally", "from_skill COMMON"));
        assertRule(1215, "DEALING_DAMAGE", "talent_skill", List.of("target has_state 承负", "actor is_ally", "from_skill SKILL"));
        assertRule(1215, "DEALING_DAMAGE", "talent_ultra", List.of("target has_state 承负", "actor is_ally", "from_skill ULTRA"));
        assertRule(1215, "BATTLE_START", "eidolon4_duration", List.of());
        assertRule(1215, "BATTLE_START", "eidolon6_talent", List.of());
        assertRule(1217, "SKILL_CAST", "skill_talisman", List.of("actor == self"));
        assertRule(1217, "ULT_CAST", "ult_tail", List.of("actor == self"));
        assertRule(1217, "BATTLE_START", "technique_attack_down", List.of("self has_state 秘技"));
        assertRule(1218, "ALLY_ATTACK", "talent_ashen_roast_and_burn", List.of("actor == self"));
        assertRule(1218, "BATTLE_START", "technique_opening_aoe_and_stack", List.of("self has_state 秘技"));
        assertRule(1218, "BATTLE_START", "level_convention", List.of());
        assertRule(1218, "ALLY_ATTACK", "talent_res_down_per_ashen_roast", List.of("actor == self"));
        assertRule(1218, "ALLY_ATTACK", "talent_vulnerability_per_ashen_roast", List.of("actor == self"));
        assertRule(1218, "ULT_CAST", "ult_domain_ult_damage_taken", List.of("actor == self"));
        assertRule(1218, "DEALING_DAMAGE", "talent_ember_tiered_taken", List.of("actor == self", "target_stacks:烬煨 >= 1.0"));
        assertRule(1220, "ALLY_ATTACK", "talent_followup_on_teammate_attack", List.of("actor is_other_ally"));
        assertRule(1220, "ALLY_ATTACK", "talent_damage_up_on_this_attack", List.of("actor is_other_ally"));
        assertRule(1220, "SKILL_CAST", "skill_repeats_the_talent_followup", List.of("actor == self"));
        assertRule(1220, "BATTLE_START", "level_convention", List.of());
        assertRule(1220, "DEALING_DAMAGE", "ult_damage_multiplier_when_broken", List.of("actor == self", "from_skill ULTRA", "target has_state 弱点击破"));
        assertRule(1220, "DEALING_DAMAGE", "ult_damage_multiplier_when_unbroken", List.of("actor == self", "from_skill ULTRA", "!target has_state 弱点击破"));
        assertRule(1220, "DEALING_DAMAGE", "trace_followup_crit_damage", List.of("actor == self"));
        assertRule(1221, "SKILL_CAST", "skill_heal", List.of("actor == self"));
        assertRule(1221, "TAKING_HIT", "talent_counter_on_being_hit", List.of("target == self"));
        assertRule(1221, "BATTLE_START", "level_convention", List.of());
        assertRule(1222, "BATTLE_START", "level_convention", List.of());
        assertRule(1222, "SKILL_CAST", "skill_party_heal", List.of("actor == self"));
        assertRule(1222, "ULT_CAST", "ult_befog_break_damage_taken", List.of("actor == self"));
        assertRule(1222, "ULT_CAST", "ult_party_heal", List.of("actor == self"));
        assertRule(1222, "ULT_CAST", "eidolon2_party_break_effect", List.of("actor == self"));
        assertRule(1223, "SKILL_CAST", "skill_marks_prey", List.of("actor == self"));
        assertRule(1223, "ALLY_ATTACK", "talent_additional_damage_on_prey", List.of("target has_state 猎物"));
        assertRule(1223, "ULT_CAST", "ult_triggers_talent_followup", List.of("actor == self"));
        assertRule(1223, "BATTLE_START", "technique_damage_up", List.of("self has_state 秘技"));
        assertRule(1223, "BATTLE_START", "eidolon1_energy_on_entry", List.of());
        assertRule(1223, "ALLY_ATTACK", "eidolon1_energy_per_additional_damage", List.of("target has_state 猎物"));
        assertRule(1223, "BATTLE_START", "level_convention", List.of());
        assertRule(1223, "SKILL_CAST", "trace_prey_followup_taken", List.of("actor == self"));
        assertRule(1223, "FOLLOW_UP", "trace_skill_point_after_followup", List.of("actor == self"));
        assertRule(1224, "SKILL_CAST", "skill_shifu_and_speed", List.of("actor == self"));
        assertRule(1224, "ALLY_ATTACK", "talent_charge_on_shifu_attack", List.of("actor has_state 师父"));
        assertRule(1224, "ULT_CAST", "talent_charge_on_shifu_ult", List.of("actor has_state 师父"));
        assertRule(1224, "BASIC_ATTACK", "basic_charge", List.of("actor == self"));
        assertRule(1224, "BATTLE_START", "technique_energy", List.of("self has_state 秘技"));
        assertRule(1224, "BATTLE_START", "level_convention", List.of());
        assertRule(1225, "SKILL_CAST", "skill_marks_foxian_prayer", List.of("actor == self"));
        assertRule(1225, "SKILL_CAST", "skill_torrid_scorch_on_self", List.of("actor == self"));
        assertRule(1225, "SKILL_CAST", "skill_break_effect_for_marked_ally", List.of("actor == self"));
        assertRule(1225, "ALLY_ATTACK", "skill_defence_down_on_marked_attack", List.of("actor has_state 狐祈"));
        assertRule(1225, "BATTLE_START", "technique_advance_and_defence_down", List.of("self has_state 秘技"));
        assertRule(1225, "BATTLE_START", "level_convention", List.of());
        assertRule(1301, "ULT_CAST", "ult_tipsy", List.of("actor == self"));
        assertRule(1301, "DEALING_DAMAGE", "enhanced_attack_down", List.of("actor == self", "from_skill_id == 8.0"));
        assertRule(1302, "BASIC_ATTACK", "talent_stack_basic", List.of("actor == self"));
        assertRule(1302, "SKILL_CAST", "talent_stack_skill", List.of("actor == self"));
        assertRule(1302, "ULT_CAST", "talent_stack_ultra", List.of("actor == self"));
        assertRule(1303, "BATTLE_START", "talent_speed_for_teammates", List.of());
        assertRule(1303, "SKILL_CAST", "skill_overtone_on_self", List.of("actor == self"));
        assertRule(1303, "BATTLE_START", "level_convention", List.of());
        assertRule(1303, "ULT_CAST", "ult_zone_all_type_res_pen", List.of("actor == self"));
        assertRule(1303, "ULT_CAST", "eidolon1_defence_ignore_in_zone", List.of("actor == self"));
        assertRule(1303, "ULT_CAST", "eidolon6_extends_the_zone", List.of("actor == self"));
        assertRule(1304, "BATTLE_START", "trace_hot_hand_opening_shield", List.of());
        assertRule(1304, "ULT_CAST", "ult_unnerved_state", List.of("actor == self"));
        assertRule(1304, "BASIC_ATTACK", "basic_all_type_res_down", List.of("actor == self"));
        assertRule(1304, "BATTLE_START", "level_convention", List.of());
        assertRule(1305, "ALLY_ATTACK", "talent_chance_followup", List.of("actor == self", "from_skill SKILL"));
        assertRule(1305, "ULT_CAST", "ult_marks_wisemans_folly", List.of("actor == self"));
        assertRule(1305, "ALLY_ATTACK", "ult_reaction_followup", List.of("actor is_other_ally", "target has_state 智者的短见"));
        assertRule(1305, "BATTLE_START", "technique_speed_down", List.of("self has_state 秘技"));
        assertRule(1305, "BATTLE_START", "level_convention", List.of());
        assertRule(1306, "SKILL_CAST", "skill_crit_damage_share_and_advance", List.of("actor == self"));
        assertRule(1306, "ULT_CAST", "ult_skill_points_and_cipher", List.of("actor == self"));
        assertRule(1306, "SKILL_POINT_SPENT", "talent_party_damage_on_spend", List.of());
        assertRule(1306, "BATTLE_START", "technique_skill_points", List.of("self has_state 秘技"));
        assertRule(1306, "BATTLE_START", "level_convention", List.of());
        assertRule(1306, "SKILL_POINT_SPENT", "eidolon2_defence_ignore_per_layer", List.of());
        assertRule(1306, "SKILL_POINT_SPENT", "talent_phantasm_stack", List.of());
        assertRule(1306, "SKILL_POINT_SPENT", "talent_phantasm_damage_taken", List.of());
        assertRule(1307, "SKILL_CAST", "skill_arcana_stack", List.of("actor == self"));
        assertRule(1307, "SKILL_CAST", "skill_defence_down", List.of("actor == self"));
        assertRule(1307, "BATTLE_START", "level_convention", List.of());
        assertRule(1308, "SKILL_CAST", "skill_slashed_dream", List.of("actor == self"));
        assertRule(1308, "BATTLE_START", "level_convention", List.of());
        assertRule(1308, "BATTLE_START", "talent_ult_damage_taken", List.of());
        assertRule(1309, "DEALING_DAMAGE", "trace_followup_crit_aura", List.of("self has_state 协奏"));
        assertRule(1310, "SKILL_CAST", "skill_action_advance", List.of("actor == self"));
        assertRule(1310, "ULT_CAST", "ult_action_advance", List.of("actor == self"));
        assertRule(1310, "BATTLE_START", "level_convention", List.of());
        assertRule(1312, "SKILL_POINT_SPENT", "talent_energy_on_skill_point_spent", List.of());
        assertRule(1312, "BATTLE_START", "level_convention", List.of());
        assertRule(1314, "BATTLE_START", "trace_reverse_repo_one_goods", List.of());
        assertRule(1314, "BATTLE_START", "technique_fifteen_goods", List.of("self has_state 秘技"));
        assertRule(1314, "BATTLE_START", "eidolon2_crit_chance_at_fifteen_goods", List.of("self_stacks:当品 >= 15.0"));
        assertRule(1315, "SKILL_CAST", "skill_standoff_on_both", List.of("actor == self"));
        assertRule(1315, "KILL", "standoff_stack_on_kill", List.of());
        assertRule(1315, "BREAK", "standoff_stack_on_break", List.of());
        assertRule(1315, "BATTLE_START", "level_convention", List.of());
        assertRule(1315, "BATTLE_START", "eidolon1_defence_ignore", List.of());
        assertRule(1317, "BREAK", "talent_charge_on_break", List.of());
        assertRule(1317, "BATTLE_START", "level_convention", List.of());
        assertRule(1317, "BATTLE_START", "talent_break_damage_taken", List.of());
        assertRule(1317, "BREAK", "trace1317103_base", List.of("self_attr:attack < 2500.0"));
        assertRule(1317, "BREAK", "trace1317103_tier1", List.of("self_attr:attack >= 2500.0", "self_attr:attack < 2600.0"));
        assertRule(1317, "BREAK", "trace1317103_tier2", List.of("self_attr:attack >= 2600.0", "self_attr:attack < 2700.0"));
        assertRule(1317, "BREAK", "trace1317103_tier3", List.of("self_attr:attack >= 2700.0", "self_attr:attack < 2800.0"));
        assertRule(1317, "BREAK", "trace1317103_tier4", List.of("self_attr:attack >= 2800.0", "self_attr:attack < 2900.0"));
        assertRule(1317, "BREAK", "trace1317103_tier5", List.of("self_attr:attack >= 2900.0", "self_attr:attack < 3000.0"));
        assertRule(1317, "BREAK", "trace1317103_tier6", List.of("self_attr:attack >= 3000.0", "self_attr:attack < 3100.0"));
        assertRule(1317, "BREAK", "trace1317103_tier7", List.of("self_attr:attack >= 3100.0", "self_attr:attack < 3200.0"));
        assertRule(1317, "BREAK", "trace1317103_tier8", List.of("self_attr:attack >= 3200.0"));
        assertRule(1321, "SKILL_CAST", "skill_domain", List.of("actor == self"));
        assertRule(1321, "BATTLE_START", "aura_all_type_res_down", List.of());
        assertRule(1401, "BATTLE_START", "technique_opening_attack", List.of("self has_state 秘技"));
        assertRule(1401, "ULT_CAST", "ult_attack_advance_and_inspiration", List.of("actor == self"));
        assertRule(1401, "BATTLE_START", "level_convention", List.of());
        assertRule(1402, "DEALING_DAMAGE", "talent_fissure_thread_bonus", List.of("actor == self", "self_summon_count >= 1.0", "target has_state 间隙织线"));
        assertRule(1402, "DEALING_DAMAGE", "talent_fissure_thread_applies_state", List.of("actor == self", "self_summon_count >= 1.0"));
        assertRule(1403, "BATTLE_START", "trace_30_energy", List.of());
        assertRule(1403, "ALLY_ATTACK", "trace_energy_per_target", List.of("actor != self", "hit_count > 0.0"));
        assertRule(1403, "ULT_CAST", "talent_followup_on_other_ult", List.of("actor is_other_ally"));
        assertRule(1403, "SKILL_CAST", "skill_numinosity", List.of("actor == self"));
        assertRule(1403, "BATTLE_START", "technique_numinosity", List.of("self has_state 秘技"));
        assertRule(1403, "FOLLOW_UP", "trace_damage_boost_after_followup", List.of("actor == self"));
        assertRule(1403, "ULT_CAST", "ult_zone_enemy_vulnerability", List.of("actor == self"));
        assertRule(1403, "BATTLE_START", "level_convention", List.of());
        assertRule(1404, "BATTLE_START", "technique_opening_aoe_and_charge", List.of("self has_state 秘技"));
        assertRule(1404, "ULT_CAST", "ult_heal_charge_and_taunt", List.of("actor == self"));
        assertRule(1404, "BATTLE_START", "level_convention", List.of());
        assertRule(1405, "ALLY_ATTACK", "eidolon1_defence_down_on_skill", List.of("actor == self", "from_skill SKILL"));
        assertRule(1405, "BATTLE_START", "level_convention", List.of());
        assertRule(1405, "SKILL_CAST", "eidolon4_attack", List.of("actor == self"));
        assertRule(1406, "SKILL_CAST", "skill_weakness_and_attack", List.of("actor == self"));
        assertRule(1406, "SKILL_CAST", "talent_patron_on_skill", List.of("actor == self"));
        assertRule(1406, "ULT_CAST", "talent_patron_on_ult", List.of("actor == self"));
        assertRule(1406, "ALLY_ATTACK", "talent_reaction_followup", List.of("actor is_other_ally", "target has_state 老主顾"));
        assertRule(1406, "BATTLE_START", "technique_opening_aoe", List.of("self has_state 秘技"));
        assertRule(1406, "DEALING_DAMAGE", "eidolon2_damage_taken", List.of("actor == self"));
        assertRule(1406, "BATTLE_START", "level_convention", List.of());
        assertRule(1406, "DEALING_DAMAGE", "trace_followup_crit_damage", List.of("actor == self"));
        assertRule(1407, "HP_LOST", "talent_damage_up_on_hp_loss", List.of());
        assertRule(1407, "BATTLE_START", "level_convention", List.of());
        assertRule(1408, "SKILL_CAST", "skill_coreflame", List.of("actor == self"));
        assertRule(1408, "BATTLE_START", "technique_energy_and_skill_point", List.of("self has_state 秘技"));
        assertRule(1408, "BATTLE_START", "level_convention", List.of());
        assertRule(1409, "ULT_CAST", "ult_state_and_max_hp", List.of("actor == self"));
        assertRule(1409, "BATTLE_START", "level_convention", List.of());
        assertRule(1410, "SKILL_CAST", "skill_damage_taken_up", List.of("actor == self"));
        assertRule(1410, "BATTLE_START", "level_convention", List.of());
        assertRule(1412, "SKILL_CAST", "skill_grants_military_merit", List.of("actor == self"));
        assertRule(1412, "SKILL_CAST", "talent_attack_share_on_marked_ally", List.of("actor == self"));
        assertRule(1412, "ALLY_ATTACK", "talent_charge_from_marked_ally", List.of("actor has_state 军功"));
        assertRule(1412, "ALLY_ATTACK", "talent_additional_damage_after_marked_attack", List.of("actor has_state 军功"));
        assertRule(1412, "ULT_CAST", "ult_charge", List.of("actor == self"));
        assertRule(1412, "BATTLE_START", "level_convention", List.of());
        assertRule(1412, "SKILL_CAST", "eidolon1_defence_ignore_for_marked", List.of("actor == self"));
        assertRule(1413, "SUMMONED", "memosprite_taunt_aggro", List.of("actor == summon"));
        assertRule(1413, "DEALING_DAMAGE", "talent_memosprite_damage_enemy_count_4", List.of("enemy_count >= 4.0", "actor == summon"));
        assertRule(1413, "DEALING_DAMAGE", "talent_memosprite_damage_enemy_count_3", List.of("enemy_count == 3.0", "actor == summon"));
        assertRule(1413, "DEALING_DAMAGE", "talent_memosprite_damage_enemy_count_2", List.of("enemy_count == 2.0", "actor == summon"));
        assertRule(1413, "DEALING_DAMAGE", "talent_memosprite_damage_enemy_count_1", List.of("enemy_count == 1.0", "actor == summon"));
        assertRule(1414, "SKILL_CAST", "skill_bondmate_and_shield", List.of("actor == self"));
        assertRule(1414, "ULT_CAST", "ult_party_shield", List.of("actor == self"));
        assertRule(1414, "BATTLE_START", "level_convention", List.of());
        assertRule(1415, "BASIC_ATTACK", "basic_recollection", List.of("actor == self"));
        assertRule(1415, "SKILL_CAST", "skill_recollection", List.of("actor == self"));
        assertRule(1415, "BATTLE_START", "talent_party_damage", List.of());
        assertRule(1415, "BATTLE_START", "level_convention", List.of());
        assertRule(1501, "BATTLE_START", "technique_opening_aoe_and_skill_points", List.of("self has_state 秘技"));
        assertRule(1501, "BATTLE_START", "level_convention", List.of());
        assertRule(1502, "CAST_SETUP", "p1502_ult_penetration", List.of("actor == self", "from_category ULTRA"));
        assertRule(1504, "ALLY_ATTACK", "talent_reaction_to_bait", List.of("actor is_other_ally", "target has_state 饲饵"));
        assertRule(1504, "BATTLE_START", "technique_opening_aoe", List.of("self has_state 秘技"));
        assertRule(1504, "SKILL_CAST", "skill_marks_the_bait", List.of("actor == self"));
        assertRule(1504, "BATTLE_START", "eidolon1_enemies_take_more", List.of());
        assertRule(1504, "BATTLE_START", "level_convention", List.of());
        assertRule(1504, "BATTLE_START", "trace_party_crit_damage_aura", List.of());
        assertRule(1504, "DEALING_DAMAGE", "trace_followup_crit_damage_extra_self", List.of("actor == self"));
        assertRule(1504, "DEALING_DAMAGE", "trace_followup_crit_damage_extra_other_ally", List.of("actor is_other_ally"));
        assertRule(1505, "BATTLE_START", "p1505_elation_value", List.of());
        assertRule(1505, "BATTLE_START", "p1505_technique_gift", List.of());
        assertRule(1505, "ENERGY_GAINED", "p1505_energy_sync", List.of());
        assertRule(1505, "DEALING_DAMAGE", "p1505_skill_elation_rider", List.of("actor == self", "from_category BPSKILL", "self_resource:好活当赏 >= 1.0"));
        assertRule(1505, "CAST_SETUP", "p1505_ult_elation_rider", List.of("actor == self", "from_category ULTRA", "self_resource:好活当赏 >= 1.0"));
        assertRule(1505, "CAST_SETUP", "p1505_ult_random_rider", List.of("actor == self", "from_category ULTRA", "self_resource:好活当赏 >= 1.0"));
        assertRule(1505, "ENERGY_GAINED", "p1505_energy_accumulator", List.of());
        assertRule(1505, "BATTLE_START", "p1505_technique_damage", List.of());
        assertRule(1505, "CAST_SETUP", "p1505_skill_laughs", List.of("actor == self", "from_category BPSKILL"));
        assertRule(1506, "CAST_SETUP", "p1506_ult_advance", List.of("actor == self", "from_category ULTRA"));
        assertRule(1506, "RESOURCE_CHANGED", "p1506_laughs_to_hidden", List.of("resource_changed:笑点"));
        assertRule(1507, "ULT_CAST", "ult_zone_and_thousand_forgings", List.of("actor == self"));
        assertRule(1507, "COUNTDOWN_TURN", "zone_ends_takes_thousand_forgings_off", List.of("actor == countdown"));
        assertRule(1507, "ULT_CAST", "eidolon1_zone_enemy_res_down", List.of());
        assertRule(1510, "SKILL_CAST", "skill_navigators_semaphore", List.of("actor == self"));
        assertRule(1510, "BATTLE_START", "level_convention", List.of());
        assertRule(1512, "BATTLE_START", "technique_advance_vibes_and_damage", List.of("self has_state 秘技"));
        assertRule(1512, "SKILL_CAST", "skill_summon_and_vibes", List.of("actor == self"));
        assertRule(1512, "BATTLE_START", "level_convention", List.of());
        assertRule(1513, "ALLY_ATTACK", "talent_fervor_on_teammate_attack", List.of("actor is_other_ally"));
        assertRule(1513, "SKILL_CAST", "skill_fervor", List.of("actor == self"));
        assertRule(1513, "ULT_CAST", "ult_fervor_and_speed", List.of("actor == self"));
        assertRule(1513, "BATTLE_START", "technique_fervor", List.of("self has_state 秘技"));
        assertRule(1513, "BATTLE_START", "level_convention", List.of());
        assertRule(8001, "BREAK", "talent_atk_on_break", List.of("actor == self"));
        assertRule(8001, "BATTLE_START", "level_convention", List.of());
        assertRule(8001, "BATTLE_START", "technique_party_heal", List.of("self has_state 秘技"));
        assertRule(8001, "BREAK", "trace_tough_defence_per_stack", List.of("actor == self"));
        assertRule(8001, "ALLY_ATTACK", "eidolon4_crit_chance_on_broken_target", List.of("actor == self", "target has_state 弱点击破"));
        assertRule(8002, "BREAK", "talent_atk_on_break", List.of("actor == self"));
        assertRule(8002, "BATTLE_START", "technique_party_heal", List.of("self has_state 秘技"));
        assertRule(8002, "BATTLE_START", "level_convention", List.of());
        assertRule(8002, "BREAK", "trace_tough_defence_per_stack", List.of("actor == self"));
        assertRule(8002, "ALLY_ATTACK", "eidolon4_crit_chance_on_broken_target", List.of("actor == self", "target has_state 弱点击破"));
        assertRule(8003, "TAKING_HIT", "talent_magma_will", List.of("target == self"));
        assertRule(8003, "BASIC_ATTACK", "talent_shield_on_basic", List.of("actor == self"));
        assertRule(8003, "SKILL_CAST", "skill_reduction_and_taunt", List.of("actor == self"));
        assertRule(8003, "ULT_CAST", "talent_shield_on_ult", List.of("actor == self"));
        assertRule(8003, "SKILL_CAST", "talent_shield_on_skill", List.of("actor == self"));
        assertRule(8003, "BATTLE_START", "technique_self_shield", List.of("self has_state 秘技"));
        assertRule(8003, "BATTLE_START", "level_convention", List.of());
        assertRule(8004, "TAKING_HIT", "talent_magma_will", List.of("target == self"));
        assertRule(8004, "BASIC_ATTACK", "talent_shield_on_basic", List.of("actor == self"));
        assertRule(8004, "SKILL_CAST", "skill_reduction_and_taunt", List.of("actor == self"));
        assertRule(8004, "ULT_CAST", "talent_shield_on_ult", List.of("actor == self"));
        assertRule(8004, "SKILL_CAST", "talent_shield_on_skill", List.of("actor == self"));
        assertRule(8004, "BATTLE_START", "technique_self_shield", List.of("self has_state 秘技"));
        assertRule(8004, "BATTLE_START", "level_convention", List.of());
        assertRule(8005, "ULT_CAST", "ult_dance", List.of("actor == self"));
        assertRule(8005, "DEALING_DAMAGE", "ult_super_break", List.of("actor has_state 伴舞", "target has_state 弱点击破"));
        assertRule(8005, "BREAK", "talent_energy_on_break", List.of());
        assertRule(8005, "BATTLE_START", "technique_breaking_effect", List.of("self has_state 秘技"));
        assertRule(8005, "BATTLE_START", "level_convention", List.of());
        assertRule(8006, "ULT_CAST", "ult_dance", List.of("actor == self"));
        assertRule(8007, "SKILL_CAST", "skill_summon_mem", List.of("actor == self"));
        assertRule(8007, "ULT_CAST", "ult_summon_mem", List.of("actor == self"));
        assertRule(8007, "BATTLE_START", "level_convention", List.of());
        assertRule(8008, "SKILL_CAST", "skill_summon_mem", List.of("actor == self"));
        assertRule(8008, "ULT_CAST", "ult_summon_mem", List.of("actor == self"));
        assertRule(8008, "BATTLE_START", "level_convention", List.of());
        assertRule(8009, "ULT_CAST", "ult_crit_damage_for_the_chosen_ally", List.of("actor == self"));
        assertRule(8009, "ALLY_ATTACK", "talent_energy_after_attack", List.of("actor == self"));
        assertRule(8009, "BATTLE_START", "level_convention", List.of());
        assertRule(8010, "ULT_CAST", "ult_crit_damage_for_the_chosen_ally", List.of("actor == self"));
        assertRule(8010, "ALLY_ATTACK", "talent_energy_after_attack", List.of("actor == self"));
        assertRule(8010, "BATTLE_START", "level_convention", List.of());
    }
}
