package com.laosun.aluminium.test;

import com.laosun.aluminium.enums.TriggerEvent;
import com.laosun.aluminium.models.Character;
import com.laosun.aluminium.models.Weapon;
import com.laosun.aluminium.utils.CharacterFactory;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

/**
 * Every light cone\u2019s loaded-tier rule conditions, asserted as PREFIXES (2026-09-30).
 *
 * <p>\u2b50 Tier semantics read off the loader: the axis is the SUPERIMPOSITION RANK, the exact rank is used, a missing
 * rank falls back to the lowest existing row, and only numeric keys are ranks -- so these come from each file\u2019s
 * smallest numeric key (what {@code Weapon.build(id, 9)} lands on).
 *
 * <p>\u2b50 Why prefixes: {@code source()} is the parser\u2019s spelling for pure-text conditions but a parse-time SNAPSHOT
 * when a condition compares against a numeric variable (measured: {@code target_hp_percent >= hp_percent} comes back as
 * {@code target_hp_percent >= 0.0}). So a value-carrying condition is pinned by NAME + OPERATOR, everything else by the
 * whole text -- and every rule is covered. Regenerate after a condition change.
 */
public class ConeConditionLiteralsTest {
    private static final int WEARER = 1210;
    private static final int RANK = 9;

    private void assertRule(int cone, String event, String id, List<String> expected) {
        Character c = CharacterFactory.create(WEARER, 80, true, Weapon.build(cone, RANK));
        var rules = c.getTriggerTable().rulesFor(TriggerEvent.valueOf(event)).stream()
                .filter(r -> r.id().equals(id)).toList();
        Assertions.assertEquals(1, rules.size(), cone + " " + id + " on " + event);
        var actual = rules.getFirst().conditions().stream().map(x -> x.source()).toList();
        Assertions.assertEquals(expected.size(), actual.size(), cone + " " + id + " (condition count)");
        for (int i = 0; i < expected.size(); i++) {
            Assertions.assertTrue(actual.get(i).startsWith(expected.get(i)),
                    cone + " " + id + " condition " + i + ": expected prefix <" + expected.get(i)
                            + "> but was <" + actual.get(i) + ">");
        }
    }

    @Test
    public void everyRuleWaitsForExactlyWhatItSays() {
        assertRule(20000, "BATTLE_START", "cone20000_crit_chance", List.of());
        assertRule(20001, "CAST_SETUP", "cone20001_heal_on_skill", List.of("actor == self", "from_skill SKILL"));
        assertRule(20001, "CAST_SETUP", "cone20001_heal_on_ult", List.of("actor == self", "from_skill ULTRA"));
        assertRule(20002, "BATTLE_START", "boost_basic_attack_damage_boost_1", List.of());
        assertRule(20002, "BATTLE_START", "boost_skill_damage_boost_1", List.of());
        assertRule(20003, "TURN_START", "cone20003_defence_base", List.of("hp_percent >="));
        assertRule(20003, "TURN_START", "cone20003_defence_below_threshold", List.of("hp_percent <"));
        assertRule(20004, "BATTLE_START", "cone20004_ehr", List.of());
        assertRule(20005, "BATTLE_START", "cone20005_party_attack", List.of());
        assertRule(20006, "BATTLE_START", "boost_ultimate_damage_boost_1", List.of());
        assertRule(20007, "KILL", "cone20007_attack_on_kill", List.of());
        assertRule(20008, "BATTLE_START", "cone20008_party_energy", List.of());
        assertRule(20009, "DEALING_DAMAGE", "shattered_home_against_healthy", List.of("actor == self", "target_hp_percent >"));
        assertRule(20010, "ULT_CAST", "cone20010_heal_on_ult", List.of());
        assertRule(20011, "DEALING_DAMAGE", "loop_against_slowed", List.of("actor == self", "target has_state 减速"));
        assertRule(20012, "BASIC_ATTACK", "cone20012_energy", List.of());
        assertRule(20013, "SKILL_CAST", "cone20013_energy_on_skill", List.of());
        assertRule(20014, "KILL", "cone20014_speed", List.of());
        assertRule(20015, "BASIC_ATTACK", "cone20015_advance_after_basic", List.of());
        assertRule(20016, "TURN_START", "cone20016_crit_below_threshold", List.of("hp_percent <"));
        assertRule(20017, "BREAK", "cone20017_heal_on_break", List.of());
        assertRule(20018, "SKILL_CAST", "cone20018_arm_next_basic", List.of("actor == self"));
        assertRule(20018, "DEALING_DAMAGE", "cone20018_spend_marker", List.of("actor == self", "self_stacks:下一次普攻待命 >= 1.0"));
        assertRule(20019, "BATTLE_START", "cone20019_party_speed", List.of());
        assertRule(20020, "ULT_CAST", "cone20020_attack_on_ult", List.of());
        assertRule(20021, "SUMMONED", "cone20021_first_summon", List.of("actor == self"));
        assertRule(20022, "TURN_START", "cone20022_memorial_on_memosprite_turn", List.of("actor == summon"));
        assertRule(20022, "KILL", "cone20022_memorial_removed_when_it_is_killed", List.of("target == summon"));
        assertRule(20024, "RESOURCE_CHANGED", "cone20024_threshold_met", List.of("actor == self", "self_resource:笑点 >= 10.0"));
        assertRule(20024, "RESOURCE_CHANGED", "cone20024_threshold_lost", List.of("actor == self", "self_resource:笑点 < 10.0"));
        assertRule(21000, "CAST_SETUP", "cone21000_heal_on_ult", List.of("actor == self", "from_skill ULTRA"));
        assertRule(21001, "DEALING_DAMAGE", "cone21001_per_debuff", List.of("actor == self", "target_debuff_count >= 1.0", "target_debuff_count < 3.0"));
        assertRule(21001, "DEALING_DAMAGE", "cone21001_at_cap", List.of("actor == self", "target_debuff_count >= 3.0"));
        assertRule(21002, "BATTLE_START", "cone21002_party_all_type_resistance", List.of());
        assertRule(21003, "BATTLE_START", "cone21003_attack", List.of());
        assertRule(21003, "BATTLE_START", "cone21003_crit_few_enemies", List.of("enemy_count <= 2.0"));
        assertRule(21004, "BATTLE_START", "cone21004_break_effect", List.of());
        assertRule(21004, "BASIC_ATTACK", "cone21004_energy", List.of());
        assertRule(21005, "BASIC_ATTACK", "moles_stack_on_basic_attack", List.of("actor == self"));
        assertRule(21005, "SKILL_CAST", "moles_stack_on_skill_cast", List.of("actor == self"));
        assertRule(21005, "ULT_CAST", "moles_stack_on_ult_cast", List.of("actor == self"));
        assertRule(21006, "BATTLE_START", "cone21006_followup_boost", List.of());
        assertRule(21006, "DEALING_DAMAGE", "cone21006_followup_extra_when_low", List.of("actor == self", "target_hp_percent <="));
        assertRule(21007, "BATTLE_START", "cone21007_healing", List.of());
        assertRule(21007, "SKILL_CAST", "cone21007_party_energy", List.of());
        assertRule(21008, "BATTLE_START", "cone21008_ehr_and_dot", List.of());
        assertRule(21009, "BATTLE_START", "landau_aggro_up", List.of());
        assertRule(21009, "BATTLE_START", "landau_damage_taken_down", List.of());
        assertRule(21010, "DEALING_DAMAGE", "cone21010_stack_on_the_target", List.of("actor == self"));
        assertRule(21010, "DEALING_DAMAGE", "cone21010_damage_per_stack", List.of("actor == self", "target_stacks:睚准 >= 1.0"));
        assertRule(21011, "DEALING_DAMAGE", "cone21011_same_element", List.of("actor is_ally", "damage_element_is_self"));
        assertRule(21012, "DEALING_DAMAGE", "cone21012_healthier_target", List.of("actor == self", "target_hp_percent >="));
        assertRule(21013, "BATTLE_START", "cone21013_energy_on_entry", List.of());
        assertRule(21013, "BATTLE_START", "cone21013_ult_damage", List.of());
        assertRule(21014, "BATTLE_START", "cone21014_effect_res", List.of());
        assertRule(21014, "BATTLE_START", "cone21014_healing_off_effect_res", List.of());
        assertRule(21015, "DEALING_DAMAGE", "cone21015_apply_the_state", List.of("actor == self", "!target has_state 攻陷"));
        assertRule(21015, "DEALING_DAMAGE", "cone21015_defence_down_while_stated", List.of("actor == self", "target has_state 攻陷"));
        assertRule(21016, "TAKING_HIT", "cone21016_burn_on_being_hit", List.of("target == self"));
        assertRule(21017, "BATTLE_START", "cone21017_basic_boost", List.of());
        assertRule(21017, "BATTLE_START", "cone21017_skill_boost", List.of());
        assertRule(21018, "ULT_CAST", "cone21018_party_advance", List.of("actor == self"));
        assertRule(21019, "BATTLE_START", "cone21019_attack", List.of());
        assertRule(21019, "KILL", "cone21019_crit_on_kill", List.of());
        assertRule(21020, "BATTLE_START", "cone21020_attack", List.of());
        assertRule(21020, "KILL", "cone21020_crit_damage_on_kill", List.of());
        assertRule(21022, "BATTLE_START", "cone21022_break_effect", List.of());
        assertRule(21022, "DEALING_DAMAGE", "cone21022_boost_vs_shocked", List.of("actor == self", "target has_state 触电"));
        assertRule(21022, "DEALING_DAMAGE", "cone21022_boost_vs_winded", List.of("actor == self", "target has_state 风化", "!target has_state 触电"));
        assertRule(21023, "BATTLE_START", "cone21023_party_damage_taken_down", List.of());
        assertRule(21023, "BATTLE_START", "cone21023_heal_lost_hp", List.of());
        assertRule(21024, "BATTLE_START", "cone21024_battle_start", List.of());
        assertRule(21026, "BATTLE_START", "cone21026_attack", List.of());
        assertRule(21026, "DEALING_DAMAGE", "cone21026_boost_vs_burning", List.of("actor == self", "target has_state 灼烧"));
        assertRule(21026, "DEALING_DAMAGE", "cone21026_boost_vs_wounded", List.of("actor == self", "target has_state 裂伤", "!target has_state 灼烧"));
        assertRule(21027, "KILL", "cone21027_attack_stack_on_kill", List.of("actor == self"));
        assertRule(21028, "BATTLE_START", "cone21028_health", List.of());
        assertRule(21028, "BASIC_ATTACK", "cone21028_party_heal", List.of());
        assertRule(21030, "DEALING_DAMAGE", "cone21030_ult_defence_scaled_damage", List.of("actor == self", "from_category ULTRA"));
        assertRule(21031, "CRIT_DEALT", "cone21031_dispel_on_crit", List.of("actor == self"));
        assertRule(21033, "BATTLE_START", "cone21033_attack", List.of());
        assertRule(21033, "KILL", "cone21033_heal_on_kill", List.of());
        assertRule(21034, "BATTLE_START", "cone21034_damage_per_energy", List.of());
        assertRule(21035, "BATTLE_START", "cone21035_break_effect", List.of());
        assertRule(21035, "BASIC_ATTACK", "cone21035_heal", List.of());
        assertRule(21036, "CAST_SETUP", "cone21036_heart_from_normal", List.of("actor == self", "from_category NORMAL"));
        assertRule(21036, "CAST_SETUP", "cone21036_heart_from_bpskill", List.of("actor == self", "from_category BPSKILL"));
        assertRule(21036, "CAST_SETUP", "cone21036_heart_from_ultra", List.of("actor == self", "from_category ULTRA"));
        assertRule(21037, "CRIT_DEALT", "cone21037_luck_on_crit", List.of("actor == self"));
        assertRule(21037, "TURN_END", "cone21037_luck_expires", List.of("actor == self"));
        assertRule(21039, "BATTLE_START", "cone21039_effect_res", List.of());
        assertRule(21039, "BATTLE_START", "cone21039_damage_per_defence", List.of());
        assertRule(21040, "ALLY_ATTACK", "cone21040_crit_vs_two_weak_targets", List.of("actor == self", "weakness_hit_count >= 2.0"));
        assertRule(21041, "DEBUFF_APPLIED", "cone21041_trick_stack", List.of("actor == self"));
        assertRule(21041, "BATTLE_START", "cone21041_attack_at_high_ehr", List.of("self_attr:effect_hit_rate >="));
        assertRule(21042, "BATTLE_START", "cone21042_permanent", List.of());
        assertRule(21042, "ULT_CAST", "cone21042_turns", List.of("actor == self"));
        assertRule(21043, "DEALING_DAMAGE", "cone21043_damage_per_shielded_ally", List.of("actor == self"));
        assertRule(21044, "DEALING_DAMAGE", "cone21044_crit_vs_defence_down", List.of("actor == self", "target_debuff:DEFENCE"));
        assertRule(21044, "DEALING_DAMAGE", "cone21044_crit_vs_slowed", List.of("actor == self", "target_debuff:SPEED"));
        assertRule(21045, "BATTLE_START", "cone21045_break_effect", List.of());
        assertRule(21045, "ULT_CAST", "cone21045_speed", List.of());
        assertRule(21046, "BATTLE_START", "cone21046_path_twins", List.of());
        assertRule(21047, "BATTLE_START", "cone21047_break_effect", List.of());
        assertRule(21047, "BATTLE_START", "cone21047_speed", List.of());
        assertRule(21048, "BATTLE_START", "cone21048_speed", List.of());
        assertRule(21048, "BASIC_ATTACK", "cone21048_energy", List.of("target has_state 弱点击破"));
        assertRule(21050, "SKILL_CAST", "cone21050_memosprite_support", List.of("actor == summon", "target is_ally"));
        assertRule(21051, "ULT_CAST", "cone21051_ult_basic_damage", List.of("actor == self"));
        assertRule(21052, "DEALING_DAMAGE", "cone21052_wearer_while_summoned", List.of("actor == self", "self_summon_count >= 1.0"));
        assertRule(21052, "DEALING_DAMAGE", "cone21052_summon_damage", List.of("actor == summon"));
        assertRule(21053, "BATTLE_START", "cone21053_shield_boost", List.of());
        assertRule(21053, "DEALING_DAMAGE", "cone21053_damage_up_while_shielded", List.of("actor is_ally", "actor has_shield"));
        assertRule(21054, "SUMMON_ATTACK", "cone21054_summon_heal_boost", List.of("actor == summon"));
        assertRule(21055, "DEALING_DAMAGE", "cone21055_healthy_attacker", List.of("actor is_ally", "actor_hp_percent >="));
        assertRule(21056, "BATTLE_START", "cone21056_party_break_damage", List.of());
        assertRule(21057, "DEALING_DAMAGE", "cone21057_summon_crit_damage", List.of("actor == summon"));
        assertRule(21058, "BATTLE_START", "boost_skill_damage_boost_rank1", List.of());
        assertRule(21058, "BATTLE_START", "boost_ultimate_damage_boost_rank1", List.of());
        assertRule(21060, "BATTLE_START", "boost_ultimate_damage_boost_rank1", List.of());
        assertRule(21060, "BATTLE_START", "boost_follow_up_damage_boost_rank1", List.of());
        assertRule(21061, "DEALING_DAMAGE", "cone21061_damage_up", List.of("actor == self"));
        assertRule(21061, "DEALING_DAMAGE", "cone21061_vulnerability", List.of("actor == self"));
        assertRule(21062, "BATTLE_START", "boost_skill_damage_boost_1", List.of());
        assertRule(21062, "BATTLE_START", "boost_follow_up_damage_boost_1", List.of());
        assertRule(21064, "CAST_SETUP", "cone21064_elation_damage_taken", List.of("actor == self", "from_category ElationDamage"));
        assertRule(21065, "CAST_SETUP", "cone21065_elation_stack", List.of("actor == self", "from_category ElationDamage"));
        assertRule(21066, "CAST_SETUP", "cone21066_def_ignore_during_elation", List.of("actor == self", "from_category ElationDamage"));
        assertRule(22000, "DEALING_DAMAGE", "cone22000_energy_after_hitting_a_lowered_target", List.of("actor == self", "target_debuff:DEFENCE"));
        assertRule(22001, "BATTLE_START", "cone22001_permanent", List.of());
        assertRule(22001, "SKILL_CAST", "cone22001_turns", List.of("actor == self"));
        assertRule(22002, "BATTLE_START", "cone22002_attack", List.of());
        assertRule(22002, "ULT_CAST", "cone22002_damage_after_ult", List.of("actor == self"));
        assertRule(22003, "HP_LOST", "cone22003_crit_after_hp_loss", List.of("target == self"));
        assertRule(22003, "HEALED", "cone22003_crit_after_heal", List.of("target == self"));
        assertRule(22004, "DEALING_DAMAGE", "cone22004_damage_per_weakness", List.of("actor == self"));
        assertRule(22005, "SKILL_CAST", "cone22005_attack_stack_on_skill", List.of("actor == self"));
        assertRule(22007, "ULT_CAST", "cone22007_party_elation_after_ult", List.of("actor == self"));
        assertRule(22008, "FOLLOW_UP", "cone22008_crit_after_follow_up", List.of("actor == self"));
        assertRule(23000, "BREAK", "cone23000_damage_up_on_break", List.of());
        assertRule(23002, "KILL", "cone23002_after_kill", List.of("actor == self"));
        assertRule(23002, "TAKING_HIT", "cone23002_after_being_hit", List.of("target == self"));
        assertRule(23003, "ULT_CAST", "cone23003_ult_count", List.of("actor == self", "target is_ally", "self_stacks:终结计数 < 2.0"));
        assertRule(23003, "ULT_CAST", "cone23003_ult_pays_out", List.of("actor == self", "target is_ally", "self_stacks:终结计数 >= 2.0"));
        assertRule(23004, "DEALING_DAMAGE", "cone23004_boost_vs_debuffed", List.of("actor == self", "target_debuff_count >= 1.0"));
        assertRule(23005, "BATTLE_START", "moment_aggro_up", List.of());
        assertRule(23006, "DEALING_DAMAGE", "cone23006_speed_stack_on_attack", List.of("actor == self"));
        assertRule(23006, "DEALING_DAMAGE", "cone23006_thread_dot", List.of("actor == self", "!target has_state 游丝"));
        assertRule(23008, "DEALING_DAMAGE", "cone23008_energy_per_target", List.of("actor == self", "damage_is_attack"));
        assertRule(23008, "ULT_CAST", "cone23008_party_speed", List.of("actor == self"));
        assertRule(23009, "TAKING_HIT", "cone23009_damage_up_after_hit", List.of("target == self"));
        assertRule(23009, "HP_CONSUMED", "cone23009_damage_up_after_price", List.of("target == self"));
        assertRule(23010, "DEALING_DAMAGE", "cone23010_skill_damage", List.of("actor == self", "from_category BPSKILL"));
        assertRule(23010, "DEALING_DAMAGE", "cone23010_ult_damage", List.of("actor == self", "from_category ULTRA"));
        assertRule(23010, "ULT_CAST", "cone23010_follow_up_damage", List.of("actor == self"));
        assertRule(23011, "HP_LOST", "cone23011_party_damage_up_when_wearer_hurt", List.of("target == self"));
        assertRule(23011, "WAVE_START", "cone23011_heal_lost_hp_per_wave", List.of());
        assertRule(23012, "BATTLE_START", "cone23012_crit_damage", List.of());
        assertRule(23014, "TAKING_HIT", "cone23014_eclipse_on_teammate_hit", List.of("target is_ally"));
        assertRule(23014, "HP_CONSUMED", "cone23014_eclipse_on_teammate_cost", List.of("actor is_ally"));
        assertRule(23014, "DEALING_DAMAGE", "cone23014_eclipse_damage", List.of("actor == self", "self_stacks:月蚀 >= 1.0"));
        assertRule(23014, "DEALING_DAMAGE", "cone23014_eclipse_full_ignore", List.of("actor == self", "self_stacks:月蚀 >= 3.0"));
        assertRule(23014, "ALLY_ATTACK", "cone23014_eclipse_spent", List.of("actor == self"));
        assertRule(23015, "BASIC_ATTACK", "cone23015_dragon_stack", List.of("actor == self"));
        assertRule(23016, "BATTLE_START", "cone23016_follow_up_damage", List.of());
        assertRule(23016, "FOLLOW_UP", "cone23016_tame_the_target", List.of("actor == self"));
        assertRule(23016, "DEALING_DAMAGE", "cone23016_crit_per_tame_layer", List.of("actor == self", "target_stacks:温驯 >= 1.0"));
        assertRule(23017, "ULT_CAST", "cone23017_heal_lowest_ally", List.of("actor is_ally"));
        assertRule(23018, "BATTLE_START", "cone23018_crit_damage", List.of());
        assertRule(23018, "ULT_CAST", "cone23018_ult_damage_per_energy", List.of("actor == self"));
        assertRule(23019, "CAST_SETUP", "cone23019_ult_damage", List.of("actor == self", "from_category ULTRA"));
        assertRule(23019, "CAST_SETUP", "cone23019_ult_skill_point", List.of("actor == self", "from_category ULTRA", "self_attr:breaking_effect >="));
        assertRule(23019, "WAVE_START", "cone23019_wave_energy", List.of());
        assertRule(23020, "DEALING_DAMAGE", "cone23020_crit_per_debuff", List.of("actor == self", "target_debuff_count >= 1.0", "target_debuff_count <= 3.0"));
        assertRule(23020, "ULT_CAST", "cone23020_debate_state", List.of("actor == self"));
        assertRule(23020, "DEALING_DAMAGE", "cone23020_ignore_defence_on_follow_up", List.of("actor == self", "self has_state 论辩"));
        assertRule(23021, "BATTLE_START", "cone23021_mask_at_battle_start", List.of());
        assertRule(23021, "SKILL_POINT_GAINED", "cone23021_flame_per_point", List.of("self_stacks:彩焰 < 4.0"));
        assertRule(23021, "SKILL_POINT_GAINED", "cone23021_flame_pays_out", List.of("self_stacks:彩焰 >= 4.0"));
        assertRule(23021, "SKILL_POINT_OVERFLOWED", "cone23021_flame_per_overflow", List.of("self_stacks:彩焰 < 4.0"));
        assertRule(23021, "SKILL_POINT_OVERFLOWED", "cone23021_flame_pays_out_overflow", List.of("self_stacks:彩焰 >= 4.0"));
        assertRule(23022, "DEALING_DAMAGE", "cone23022_seer_from_dot_1", List.of("actor == self", "target has_state 风化"));
        assertRule(23022, "DEALING_DAMAGE", "cone23022_seer_from_dot_2", List.of("actor == self", "target has_state 灼烧"));
        assertRule(23022, "DEALING_DAMAGE", "cone23022_seer_from_dot_3", List.of("actor == self", "target has_state 触电"));
        assertRule(23022, "DEALING_DAMAGE", "cone23022_seer_from_dot_4", List.of("actor == self", "target has_state 裂伤"));
        assertRule(23022, "DEALING_DAMAGE", "cone23022_dot_ignores_defence", List.of("actor == self", "self_stacks:先知 >= 1.0"));
        assertRule(23024, "DEALING_DAMAGE", "cone23024_bubble", List.of("actor == self"));
        assertRule(23024, "DEALING_DAMAGE", "cone23024_bubble_damage", List.of("actor == self", "target has_state 泡影"));
        assertRule(23024, "DEALING_DAMAGE", "cone23024_ult_extra", List.of("actor == self", "from_category ULTRA"));
        assertRule(23025, "BREAK", "cone23025_collapse_on_break", List.of("actor == self"));
        assertRule(23025, "BREAK", "cone23025_collapse_slows", List.of("actor == self"));
        assertRule(23027, "DEALING_DAMAGE", "cone23027_break_ignores_defence", List.of("actor == self"));
        assertRule(23029, "DEALING_DAMAGE", "cone23029_armor_break", List.of("actor == self"));
        assertRule(23030, "BATTLE_START", "cone23030_aggro_up", List.of());
        assertRule(23030, "ULT_CAST", "cone23030_fire_dance", List.of("actor == self"));
        assertRule(23031, "FOLLOW_UP", "cone23031_glow_on_follow_up", List.of("actor == self"));
        assertRule(23031, "DEALING_DAMAGE", "cone23031_ult_defence_ignore", List.of("actor == self", "from_category ULTRA"));
        assertRule(23031, "TURN_END", "cone23031_glow_decay", List.of("actor == self"));
        assertRule(23032, "ULT_CAST", "cone23032_forget_worry", List.of("actor == self"));
        assertRule(23032, "DEALING_DAMAGE", "cone23032_damage_up_vs_forgetful", List.of("target has_state 忘忧"));
        assertRule(23032, "DEALING_DAMAGE", "cone23032_extra_at_high_break", List.of("target has_state 忘忧", "self_attr:breaking_effect >="));
        assertRule(23033, "BATTLE_START", "cone23033_energy_at_start", List.of());
        assertRule(23033, "ULT_CAST", "cone23033_mine_on_ult", List.of("actor == self"));
        assertRule(23033, "ALLY_ATTACK", "cone23033_basic_count", List.of("actor == self", "from_category Normal", "self_stacks:普攻计数 < 2.0"));
        assertRule(23033, "ALLY_ATTACK", "cone23033_mine_pays_out", List.of("actor == self", "from_category Normal", "self_stacks:普攻计数 >= 2.0"));
        assertRule(23034, "SKILL_CAST", "cone23034_chant_for_the_target_skill", List.of("actor == self", "target is_ally"));
        assertRule(23034, "ULT_CAST", "cone23034_chant_for_the_target_ult", List.of("actor == self", "target is_ally"));
        assertRule(23035, "BREAK", "cone23035_burn_the_broken", List.of());
        assertRule(23036, "ALLY_ATTACK", "cone23036_wearer_weaves", List.of("actor == self"));
        assertRule(23036, "ALLY_ATTACK", "cone23036_summon_weaves", List.of("actor == summon"));
        assertRule(23036, "DEALING_DAMAGE", "cone23036_brocade_crit_damage", List.of("actor == self", "self_stacks:织锦 >= 1.0"));
        assertRule(23036, "DEALING_DAMAGE", "cone23036_cap_basic_attack", List.of("actor == self", "from_category Normal", "self_stacks:织锦 >= 6.0"));
        assertRule(23037, "ULT_CAST", "cone23037_skill_and_ult_damage_up", List.of("actor == self"));
        assertRule(23038, "FOLLOW_UP", "cone23038_after_follow_up", List.of());
        assertRule(23038, "BATTLE_START", "cone23038_at_battle_start", List.of());
        assertRule(23040, "HP_LOST", "cone23040_flower_from_wearer", List.of("actor == self"));
        assertRule(23040, "HP_LOST", "cone23040_flower_from_summon", List.of("actor == summon"));
        assertRule(23041, "TURN_START", "cone23041_turn_energy", List.of());
        assertRule(23041, "DEALING_DAMAGE", "cone23041_defence_down", List.of("actor == self"));
        assertRule(23044, "DEALING_DAMAGE", "cone23044_defence_ignore", List.of("actor == self"));
        assertRule(23044, "ULT_CAST", "cone23044_sun_on_ult", List.of("actor == self"));
        assertRule(23044, "TURN_START", "cone23044_sun_off_at_turn_start", List.of("actor == self"));
        assertRule(23044, "DEALING_DAMAGE", "cone23044_sun_damage", List.of("actor == self", "self_stacks:烈阳 >= 1.0"));
        assertRule(23046, "CAST_SETUP", "cone23046_skill_stacks", List.of("actor == self", "from_category BPSKILL"));
        assertRule(23051, "CAST_SETUP", "cone23051_ult_heal", List.of("actor == self", "from_category ULTRA"));
        assertRule(23052, "SKILL_CAST", "cone23052_blank_on_ally", List.of("actor == summon", "target is_ally"));
        assertRule(23052, "SKILL_CAST", "cone23052_poem_on_enemy", List.of("actor == summon", "!target is_ally"));
        assertRule(23053, "SKILL_POINT_SPENT", "cone23053_spent_stack", List.of("self_stacks:消耗层数 < 4.0"));
        assertRule(23053, "DEALING_DAMAGE", "cone23053_def_ignore_per_stack", List.of("actor == self"));
        assertRule(23053, "SKILL_POINT_SPENT", "cone23053_turn_spend_count", List.of("self_stacks:本回合消耗 < 4.0"));
        assertRule(23053, "SKILL_POINT_SPENT", "cone23053_turn_spend_pays_out", List.of("self_stacks:本回合消耗 >= 4.0"));
        assertRule(23057, "DEALING_DAMAGE", "cone23057_elation_def_ignore", List.of("actor == self"));
        assertRule(23057, "ULT_CAST", "cone23057_laughter_on_self_ult", List.of("actor == self", "target == self", "self_stacks:笑点已触发 < 1.0"));
        assertRule(23057, "ALLY_ATTACK", "cone23057_normal_attack_count", List.of("actor == self", "from_category Normal", "self_stacks:普攻计数 < 3.0"));
        assertRule(23057, "ALLY_ATTACK", "cone23057_normal_attack_reset", List.of("actor == self", "from_category Normal", "self_stacks:普攻计数 >= 3.0"));
        assertRule(23058, "CAST_SETUP", "cone23058_elation_cast_damage_taken", List.of("actor == self", "from_category ElationDamage"));
        assertRule(23061, "SKILL_POINT_SPENT", "cone23061_turn_spend_count", List.of("actor is_ally", "actor_stacks:本回合消耗 < 4.0"));
        assertRule(23061, "SKILL_POINT_SPENT", "cone23061_crown_pays_out", List.of("actor is_ally", "actor_stacks:本回合消耗 >= 4.0"));
        assertRule(23061, "DEALING_DAMAGE", "cone23061_skill_damage_boost", List.of("actor == self", "from_category BPSKILL", "self has_state 闪耀王冠"));
        assertRule(23063, "CAST_SETUP", "cone23063_ult_skill_point", List.of("actor == self", "from_category ULTRA"));
        assertRule(23063, "BATTLE_START", "cone23063_battle_advance", List.of());
        assertRule(23064, "CAST_SETUP", "cone23064_wind_gust", List.of("actor == self", "from_category ElationDamage"));
        assertRule(23064, "WAVE_START", "cone23064_skill_point_per_wave", List.of());
        assertRule(23064, "CAST_SETUP", "cone23064_elation_cast_count", List.of("actor == self", "from_category ElationDamage", "self_stacks:欢愉技计数 < 3.0"));
        assertRule(23064, "CAST_SETUP", "cone23064_skill_point_per_three_casts", List.of("actor == self", "from_category ElationDamage", "self_stacks:欢愉技计数 >= 3.0"));
        assertRule(24000, "ALLY_ATTACK", "cone24000_attack_per_attack", List.of("actor == self"));
        assertRule(24000, "BREAK", "cone24000_damage_after_break", List.of("actor == self"));
        assertRule(24001, "BATTLE_START", "cone24001_crit", List.of());
        assertRule(24001, "DEALING_DAMAGE", "cone24001_crit_vs_low_hp", List.of("actor == self", "target_hp_percent <="));
        assertRule(24001, "KILL", "cone24001_attack_after_kill", List.of());
        assertRule(24002, "TAKING_HIT", "cone24002_shield_when_unshielded", List.of("target == self", "!self has_shield"));
        assertRule(24003, "CAST_SETUP", "cone24003_ult_dot", List.of("actor == self", "from_category ULTRA"));
        assertRule(24005, "SKILL_CAST", "cone24005_party_damage_after_skill", List.of("actor == self"));
        assertRule(24006, "SKILL_CAST", "cone24006_ally_elation_on_skill", List.of("actor == self", "target is_ally"));
        assertRule(24006, "ULT_CAST", "cone24006_ally_elation_on_ult", List.of("actor == self", "target is_ally"));
    }
}
